using LinearAlgebra
using JSON
using Statistics
using Plots

data = JSON.parsefile("tomo_data.json")

N = data["N"].data
npixels = data["npixels"].data
y = Float64.(data["y"].data)
line_pixel_lengths = Float64.(reduce(hcat, data["line_pixel_lengths"].data)') # this line to read a sparse array is generated by AI
L = line_pixel_lengths'
x = L \ y
x_mat = reshape(x, npixels, npixels)
heatmap(x_mat, yflip=true, aspect_ratio=:equal, color=:gist_gray, cbar=:none, framestyle=:none)
savefig("tomo_reconstruction.png")